<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitab5bdb0d42174993cc30a91f29e84dec
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Carbon_Fields\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Carbon_Fields\\' => 
        array (
            0 => __DIR__ . '/..' . '/htmlburger/carbon-fields/core',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitab5bdb0d42174993cc30a91f29e84dec::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitab5bdb0d42174993cc30a91f29e84dec::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitab5bdb0d42174993cc30a91f29e84dec::$classMap;

        }, null, ClassLoader::class);
    }
}
